import "./globals.css";
import { Bodoni_Moda, Gwendolyn, Quicksand } from 'next/font/google';

const bodoni = Bodoni_Moda({ subsets: ['latin'], weight: ['400', '500', '700'] });
const gwendolyn = Gwendolyn({ subsets: ['latin'], weight: ['400', '700'] });
const quicksand = Quicksand({ subsets: ['latin'], weight: ['300', '400', '500', '600', '700'] });


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${quicksand.className} ${bodoni.className} ${gwendolyn.className}`}>
      <head>
        <script src="https://static.elfsight.com/platform/platform.js" async></script>
      </head>
      <body>{children}</body>
    </html>
  );
}



export const metadata = {
  title: "Medical Tourism Tunisia",
  description: "Generated by create next app",
};
